apiVersion: v1
kind: Pod
metadata:
  name: container-limit-demo
  namespace: lim-example
spec:
  containers:
  - name: container-limit-demo-ctr
    image: polinux/stress
    resources:
      limits:
        cpu: "1"
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
